import { table } from "console";

const CONTENT = {
    en: {
        login: {
            title: "Welcome Back!",
            subtitle: "Please enter your details",
            email: "Email",
            password: "Password",
            emailPlaceholder: "Enter your email",
            passwordPlaceholder: "Enter your password",
            buttonText: "Login",
            buttonTextLoading: "Signing in...",
            forgotPassword: "Forgot Password?",
            noAccount: "Don't have an account? Sign Up",
            errors: {
                required: "All fields are required",
                invalidEmail: "Please enter a valid email address",
                invalidCredentials: "Invalid email or password",
                networkError: "Network error. Please check your connection.",
                unknownError: "An error occurred. Please try again."
            }
        },
        tabs: {
            home: "Home",
            orders: "Orders",
            profile: "Profile",
            scan: "Scan",
            tables: "Tables",
        },
        waiterHome: {
            kitchenAlerts: "Kitchen Alerts",
            newOrders: "You have {count} new orders",
            viewOrdersButton: "View Orders",
            kitchenAlertsContent: {
                ready: "Order #{order_id} is ready for table {table}",
                delayed: "Order #{order_id} is delayed for table {table}",
                preparing: "Order #{order_id} is being prepared for table {table}",
                heading: "table {table} - Order #{order_id}",
                servedButton: "Mark as Served",
            },
            quickActions: "Quick Actions",
            scanOrderQR: "Scan Order QR Code",
            addAnOrder: "Add an Order",
        },
        menuModalContent: {
            tableLabel: "Table: ",
            searchPlaceholder: "Search menu...",
            all: "All",
            selectItems: "Select items to add to order",
            loading: "Loading menu...",
            unavailable: "Unavailable",
            viewOrder: "View Order",
            orderSummary: "Order Summary",
            items: "items",
            subtotal: "Subtotal",
            total: "Total",
            addMore: "Add More",
            confirmOrder: "Confirm Order",
        },
        menuItemConfig: {
            sizeVariant: "Size / Variant",
            extrasAddons: "Extras & Add-ons",
            specialInstructions: "Special Instructions",
            specialInstructionsPlaceholder: "E.g., No onions, extra spicy, well done...",
            addToOrder: "Add to Order",
        },
        ordersPage: {
            manageOrders: "Manage orders",
            tables: "tables",
            live: "Live",
            available: "Available",
            occupied: "Occupied",
            pending: "Pending",
            ready: "Ready",
            table: "Table",
            orders: "orders",
            noOrders: "No orders",
            noTablesFound: "No Tables Found",
            noTablesDesc: "Configure your restaurant tables in settings to start managing orders.",
            loadingTables: "Loading tables...",
            orderSuccess: "Order created successfully!",
            orderError: "Failed to create order",
        },
        myOrdersPage: {
            title: "My Orders",
            ordersCount: "orders",
            loading: "Loading orders...",
            noOrders: "No Orders Yet",
            noOrdersDesc: "Orders you create will appear here.",
            table: "Table",
            total: "Total",
            today: "Today",
            yesterday: "Yesterday",
            markAsServed: "Mark as Served",
            markAsPaid: "Mark as Paid",
            filterAll: "All Orders",
            statusPending: "Pending",
            statusValidated: "Validated",
            statusPreparing: "Preparing",
            statusReady: "Ready",
            statusServed: "Served",
            statusPaid: "Paid",
            statusCanceled: "Canceled",
            // Order Actions
            orderActions: "Order Actions",
            editOrder: "Edit Order",
            editNotes: "Edit Notes",
            cancelOrder: "Cancel Order",
            deleteOrder: "Delete Order",
            viewDetails: "View Details",
            // Confirmation dialogs
            confirmCancel: "Cancel this order?",
            confirmCancelDesc: "This action cannot be undone. The kitchen will be notified.",
            confirmDelete: "Delete this order?",
            confirmDeleteDesc: "This will permanently remove the order from the system.",
            confirmServed: "Mark as served?",
            confirmServedDesc: "Confirm that this order has been delivered to the table.",
            confirmPaid: "Mark as paid?",
            confirmPaidDesc: "Confirm that this order has been paid by the customer.",
            yes: "Yes",
            no: "No",
            confirm: "Confirm",
            cancel: "Cancel",
            // Toast messages
            orderCanceled: "Order canceled successfully",
            orderDeleted: "Order deleted successfully",
            orderMarkedServed: "Order marked as served",
            orderMarkedPaid: "Order marked as paid",
            notesUpdated: "Notes updated successfully",
            actionFailed: "Action failed. Please try again.",
            // Notes Modal
            customerNotes: "Customer Notes",
            waiterNotes: "Waiter Notes",
            customerNotesPlaceholder: "Add customer preferences or requests...",
            waiterNotesPlaceholder: "Add your notes about this order...",
            saveNotes: "Save Notes",
            cancellationReason: "Cancellation Reason",
            cancellationReasonPlaceholder: "Why is this order being canceled?",
        },
        profilePage: {
            title: "Profile",
            personalInfo: "Personal Information",
            name: "Name",
            email: "Email",
            phone: "Phone",
            role: "Role",
            restaurant: "Restaurant",
            memberSince: "Member Since",
            settings: "Settings",
            language: "Language",
            notifications: "Notifications",
            darkMode: "Dark Mode",
            account: "Account",
            editProfile: "Edit Profile",
            changePassword: "Change Password",
            logout: "Logout",
            logoutConfirm: "Are you sure you want to logout?",
            version: "Version",
            support: "Support & Help",
            privacyPolicy: "Privacy Policy",
            termsOfService: "Terms of Service",
            active: "Active",
            inactive: "Inactive",
        },
        scanPage: {
            title: "Scan Order",
            subtitle: "Scan customer's QR code to review their order",
            scanning: "Scanning...",
            pointCamera: "Point your camera at the QR code",
            permissionDenied: "Camera permission denied",
            permissionDeniedDesc: "Please allow camera access to scan QR codes",
            retryPermission: "Allow Camera",
            invalidQR: "Invalid QR Code",
            invalidQRDesc: "This QR code doesn't contain a valid order",
            expiredQR: "QR Code Expired",
            expiredQRDesc: "This order has expired. Ask the customer to generate a new one.",
            wrongRestaurant: "Wrong Restaurant",
            wrongRestaurantDesc: "This order is for a different restaurant",
            scanAgain: "Scan Again",
            // Order Review
            orderReview: "Order Review",
            table: "Table",
            items: "items",
            customerNotes: "Customer Notes",
            waiterNotes: "Waiter Notes",
            waiterNotesPlaceholder: "Add notes about this order...",
            noCustomerNotes: "No customer notes",
            // Item actions
            editItem: "Edit Item",
            removeItem: "Remove",
            confirmRemove: "Remove this item?",
            confirmRemoveDesc: "This will remove the item from the order",
            // Edit modal
            selectVariant: "Select Variant",
            selectModifiers: "Modifiers",
            quantity: "Quantity",
            specialInstructions: "Special Instructions",
            specialInstructionsPlaceholder: "e.g., No onions, extra sauce...",
            saveChanges: "Save Changes",
            // Order actions
            addMoreItems: "Add More Items",
            confirmOrder: "Confirm & Send to Kitchen",
            orderTotal: "Order Total",
            subtotal: "Subtotal",
            // Success/Error states
            orderCreated: "Order created successfully!",
            orderFailed: "Failed to create order",
            creatingOrder: "Creating order...",
            // Empty state
            noItemsInOrder: "No items in order",
            noItemsDesc: "All items have been removed from this order",
        },
        kitchenPage: {
            // Dashboard
            chef: "Chef",
            pendingOrders: "Pending",
            preparingOrders: "Preparing",
            newOrders: "New Orders",
            inProgress: "In Progress",
            viewAll: "View All",
            noNewOrders: "No new orders",
            noNewOrdersDesc: "New orders will appear here",
            noPreparingOrders: "No orders in progress",
            noPreparingOrdersDesc: "Orders being prepared will appear here",
            // Orders page
            ordersTitle: "Kitchen Orders",
            ordersCount: "orders",
            loading: "Loading orders...",
            noOrders: "No Orders",
            noOrdersDesc: "There are no orders matching your filter",
            filterAll: "All",
            // Statuses
            statusPending: "Pending",
            statusPreparing: "Preparing",
            statusReady: "Ready",
            // Order card
            table: "Table",
            items: "items",
            justNow: "Just now",
            minutesAgo: "min ago",
            customerNotes: "Customer Notes",
            waiterNotes: "Waiter Notes",
            specialNote: "Special Note",
            startPreparing: "Start Preparing",
            markReady: "Mark as Ready",
            // Notifications
            newOrderAlert: "New Order!",
            newOrdersWaiting: "new orders waiting",
            viewNow: "View Now",
        }
    },
    ar: {
        login: {
            title: "مرحبًا بعودتك!",
            subtitle: "يرجى إدخال تفاصيلك",
            email: "البريد الإلكتروني",
            password: "كلمة المرور",
            emailPlaceholder: "أدخل بريدك الإلكتروني",
            passwordPlaceholder: "أدخل كلمة المرور الخاصة بك",
            buttonText: "تسجيل الدخول",
            buttonTextLoading: "جاري تسجيل الدخول...",
            forgotPassword: "هل نسيت كلمة المرور؟",
            noAccount: "ليس لديك حساب؟ سجل الآن",
            errors: {
                required: "جميع الحقول مطلوبة",
                invalidEmail: "يرجى إدخال بريد إلكتروني صحيح",
                invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
                networkError: "خطأ في الشبكة. يرجى التحقق من اتصالك.",
                unknownError: "حدث خطأ. يرجى المحاولة مرة أخرى."
            }
        },
        tabs: {
            home: "الرئيسية",
            orders: "الطلبات",
            profile: "ملفي",
            scan: "المسح",
            tables: "الطاولات",
        },
        waiterHome: {
            kitchenAlerts: "تنبيهات المطبخ",
            newOrders: "لديك {count} طلبات جديدة",
            viewOrdersButton: "عرض الطلبات",
            kitchenAlertsContent: {
                ready: "الطلب #{order_id} جاهز للطاولة {table}",
                delayed: "الطلب #{order_id} متأخر للطاولة {table}",
                preparing: "الطلب #{order_id} قيد التحضير للطاولة {table}",
                heading: "الطاولة {table} - الطلب #{order_id}",
                servedButton: "وضع علامة كمقدم",
            },
            quickActions: "إجراءات سريعة",
            scanOrderQR: "مسح رمز الاستجابة السريعة للطلب",
            addAnOrder: "إضافة طلب",
        },
        menuModalContent: {
            tableLabel: "الطاولة: ",
            searchPlaceholder: "ابحث في القائمة...",
            all: "الكل",
            selectItems: "اختر العناصر لإضافتها للطلب",
            loading: "جاري تحميل القائمة...",
            unavailable: "غير متوفر",
            viewOrder: "عرض الطلب",
            orderSummary: "ملخص الطلب",
            items: "عناصر",
            subtotal: "المجموع الفرعي",
            total: "المجموع",
            addMore: "أضف المزيد",
            confirmOrder: "تأكيد الطلب",
        },
        menuItemConfig: {
            sizeVariant: "الحجم / النوع",
            extrasAddons: "الإضافات",
            specialInstructions: "تعليمات خاصة",
            specialInstructionsPlaceholder: "مثال: بدون بصل، حار جداً، مطهو جيداً...",
            addToOrder: "أضف للطلب",
        },
        ordersPage: {
            manageOrders: "إدارة الطلبات",
            tables: "طاولات",
            live: "مباشر",
            available: "متاح",
            occupied: "مشغول",
            pending: "قيد الانتظار",
            ready: "جاهز",
            table: "طاولة",
            orders: "طلبات",
            noOrders: "لا توجد طلبات",
            noTablesFound: "لم يتم العثور على طاولات",
            noTablesDesc: "قم بتكوين طاولات مطعمك في الإعدادات لبدء إدارة الطلبات.",
            loadingTables: "جاري تحميل الطاولات...",
            orderSuccess: "تم إنشاء الطلب بنجاح!",
            orderError: "فشل في إنشاء الطلب",
        },
        myOrdersPage: {
            title: "طلباتي",
            ordersCount: "طلب",
            loading: "جاري تحميل الطلبات...",
            noOrders: "لا توجد طلبات بعد",
            noOrdersDesc: "ستظهر الطلبات التي تنشئها هنا.",
            table: "طاولة",
            total: "المجموع",
            today: "اليوم",
            yesterday: "أمس",
            markAsServed: "تحديد كمقدم",
            markAsPaid: "تحديد كمدفوع",
            filterAll: "جميع الطلبات",
            statusPending: "قيد الانتظار",
            statusValidated: "تم التحقق",
            statusPreparing: "قيد التحضير",
            statusReady: "جاهز",
            statusServed: "تم التقديم",
            statusPaid: "مدفوع",
            statusCanceled: "ملغى",
            // Order Actions
            orderActions: "إجراءات الطلب",
            editOrder: "تعديل الطلب",
            editNotes: "تعديل الملاحظات",
            cancelOrder: "إلغاء الطلب",
            deleteOrder: "حذف الطلب",
            viewDetails: "عرض التفاصيل",
            // Confirmation dialogs
            confirmCancel: "إلغاء هذا الطلب؟",
            confirmCancelDesc: "لا يمكن التراجع عن هذا الإجراء. سيتم إخطار المطبخ.",
            confirmDelete: "حذف هذا الطلب؟",
            confirmDeleteDesc: "سيتم حذف الطلب نهائياً من النظام.",
            confirmServed: "تحديد كمقدم؟",
            confirmServedDesc: "تأكيد أن هذا الطلب تم تقديمه للطاولة.",
            confirmPaid: "تحديد كمدفوع؟",
            confirmPaidDesc: "تأكيد أن هذا الطلب تم دفعه من قبل العميل.",
            yes: "نعم",
            no: "لا",
            confirm: "تأكيد",
            cancel: "إلغاء",
            // Toast messages
            orderCanceled: "تم إلغاء الطلب بنجاح",
            orderDeleted: "تم حذف الطلب بنجاح",
            orderMarkedServed: "تم تحديد الطلب كمقدم",
            orderMarkedPaid: "تم تحديد الطلب كمدفوع",
            notesUpdated: "تم تحديث الملاحظات بنجاح",
            actionFailed: "فشل الإجراء. يرجى المحاولة مرة أخرى.",
            // Notes Modal
            customerNotes: "ملاحظات العميل",
            waiterNotes: "ملاحظات النادل",
            customerNotesPlaceholder: "أضف تفضيلات أو طلبات العميل...",
            waiterNotesPlaceholder: "أضف ملاحظاتك حول هذا الطلب...",
            saveNotes: "حفظ الملاحظات",
            cancellationReason: "سبب الإلغاء",
            cancellationReasonPlaceholder: "لماذا يتم إلغاء هذا الطلب؟",
        },
        profilePage: {
            title: "الملف الشخصي",
            personalInfo: "المعلومات الشخصية",
            name: "الاسم",
            email: "البريد الإلكتروني",
            phone: "الهاتف",
            role: "الدور",
            restaurant: "المطعم",
            memberSince: "عضو منذ",
            settings: "الإعدادات",
            language: "اللغة",
            notifications: "الإشعارات",
            darkMode: "الوضع الداكن",
            account: "الحساب",
            editProfile: "تعديل الملف الشخصي",
            changePassword: "تغيير كلمة المرور",
            logout: "تسجيل الخروج",
            logoutConfirm: "هل أنت متأكد أنك تريد تسجيل الخروج؟",
            version: "الإصدار",
            support: "الدعم والمساعدة",
            privacyPolicy: "سياسة الخصوصية",
            termsOfService: "شروط الخدمة",
            active: "نشط",
            inactive: "غير نشط",
        },
        scanPage: {
            title: "مسح الطلب",
            subtitle: "امسح رمز QR الخاص بالعميل لمراجعة طلبه",
            scanning: "جاري المسح...",
            pointCamera: "وجّه الكاميرا نحو رمز QR",
            permissionDenied: "تم رفض إذن الكاميرا",
            permissionDeniedDesc: "يرجى السماح بالوصول للكاميرا لمسح رموز QR",
            retryPermission: "السماح للكاميرا",
            invalidQR: "رمز QR غير صالح",
            invalidQRDesc: "رمز QR هذا لا يحتوي على طلب صالح",
            expiredQR: "رمز QR منتهي الصلاحية",
            expiredQRDesc: "انتهت صلاحية هذا الطلب. اطلب من العميل إنشاء رمز جديد.",
            wrongRestaurant: "مطعم خاطئ",
            wrongRestaurantDesc: "هذا الطلب لمطعم مختلف",
            scanAgain: "مسح مرة أخرى",
            // Order Review
            orderReview: "مراجعة الطلب",
            table: "طاولة",
            items: "عناصر",
            customerNotes: "ملاحظات العميل",
            waiterNotes: "ملاحظات النادل",
            waiterNotesPlaceholder: "أضف ملاحظات حول هذا الطلب...",
            noCustomerNotes: "لا توجد ملاحظات من العميل",
            // Item actions
            editItem: "تعديل العنصر",
            removeItem: "حذف",
            confirmRemove: "حذف هذا العنصر؟",
            confirmRemoveDesc: "سيتم حذف العنصر من الطلب",
            // Edit modal
            selectVariant: "اختر الحجم",
            selectModifiers: "الإضافات",
            quantity: "الكمية",
            specialInstructions: "تعليمات خاصة",
            specialInstructionsPlaceholder: "مثال: بدون بصل، صلصة إضافية...",
            saveChanges: "حفظ التغييرات",
            // Order actions
            addMoreItems: "إضافة المزيد",
            confirmOrder: "تأكيد وإرسال للمطبخ",
            orderTotal: "إجمالي الطلب",
            subtotal: "المجموع الفرعي",
            // Success/Error states
            orderCreated: "تم إنشاء الطلب بنجاح!",
            orderFailed: "فشل في إنشاء الطلب",
            creatingOrder: "جاري إنشاء الطلب...",
            // Empty state
            noItemsInOrder: "لا توجد عناصر في الطلب",
            noItemsDesc: "تم حذف جميع العناصر من هذا الطلب",
        },
        kitchenPage: {
            // Dashboard
            chef: "الشيف",
            pendingOrders: "قيد الانتظار",
            preparingOrders: "قيد التحضير",
            newOrders: "طلبات جديدة",
            inProgress: "قيد التنفيذ",
            viewAll: "عرض الكل",
            noNewOrders: "لا توجد طلبات جديدة",
            noNewOrdersDesc: "ستظهر الطلبات الجديدة هنا",
            noPreparingOrders: "لا توجد طلبات قيد التحضير",
            noPreparingOrdersDesc: "ستظهر الطلبات قيد التحضير هنا",
            // Orders page
            ordersTitle: "طلبات المطبخ",
            ordersCount: "طلب",
            loading: "جاري تحميل الطلبات...",
            noOrders: "لا توجد طلبات",
            noOrdersDesc: "لا توجد طلبات مطابقة للفلتر",
            filterAll: "الكل",
            // Statuses
            statusPending: "قيد الانتظار",
            statusPreparing: "قيد التحضير",
            statusReady: "جاهز",
            // Order card
            table: "طاولة",
            items: "عناصر",
            justNow: "الآن",
            minutesAgo: "دقيقة",
            customerNotes: "ملاحظات العميل",
            waiterNotes: "ملاحظات النادل",
            specialNote: "ملاحظة خاصة",
            startPreparing: "بدء التحضير",
            markReady: "تعيين كجاهز",
            // Notifications
            newOrderAlert: "طلب جديد!",
            newOrdersWaiting: "طلبات جديدة بانتظارك",
            viewNow: "عرض الآن",
        }
    },
    fr: {
        login: {
            title: "Bon Retour!",
            subtitle: "Veuillez entrer vos informations",
            email: "Email",
            password: "Mot de passe",
            emailPlaceholder: "Entrez votre email",
            passwordPlaceholder: "Entrez votre mot de passe",
            buttonText: "Connexion",
            buttonTextLoading: "Connexion en cours...",
            forgotPassword: "Mot de passe oublié?",
            noAccount: "Pas de compte? Inscrivez-vous",
            errors: {
                required: "Tous les champs sont requis",
                invalidEmail: "Veuillez entrer une adresse email valide",
                invalidCredentials: "Email ou mot de passe invalide",
                networkError: "Erreur réseau. Veuillez vérifier votre connexion.",
                unknownError: "Une erreur s'est produite. Veuillez réessayer."
            }
        },
        tabs: {
            home: "Accueil",
            orders: "Commandes",
            profile: "Profil",
            scan: "Scanner",
            tables: "Tables",
        },
        waiterHome: {
            kitchenAlerts: "Alertes Cuisine",
            newOrders: "Vous avez {count} nouvelles commandes",
            viewOrdersButton: "Voir les Commandes",
            kitchenAlertsContent: {
                ready: "Commande #{order_id} prête pour table {table}",
                delayed: "Commande #{order_id} retardée pour table {table}",
                preparing: "Commande #{order_id} en préparation pour table {table}",
                heading: "Table {table} - Commande #{order_id}",
                servedButton: "Marquer comme Servi",
            },
            quickActions: "Actions Rapides",
            scanOrderQR: "Scanner le Code QR",
            addAnOrder: "Ajouter une Commande",
        },
        menuModalContent: {
            tableLabel: "Table: ",
            searchPlaceholder: "Rechercher dans le menu...",
            all: "Tout",
            selectItems: "Sélectionnez les articles à ajouter",
            loading: "Chargement du menu...",
            unavailable: "Indisponible",
            viewOrder: "Voir la Commande",
            orderSummary: "Résumé de la Commande",
            items: "articles",
            subtotal: "Sous-total",
            total: "Total",
            addMore: "Ajouter Plus",
            confirmOrder: "Confirmer la Commande",
        },
        menuItemConfig: {
            sizeVariant: "Taille / Variante",
            extrasAddons: "Extras & Suppléments",
            specialInstructions: "Instructions Spéciales",
            specialInstructionsPlaceholder: "Ex: Sans oignons, très épicé, bien cuit...",
            addToOrder: "Ajouter à la Commande",
        },
        ordersPage: {
            manageOrders: "Gérer les commandes",
            tables: "tables",
            live: "En direct",
            available: "Disponible",
            occupied: "Occupé",
            pending: "En attente",
            ready: "Prêt",
            table: "Table",
            orders: "commandes",
            noOrders: "Aucune commande",
            noTablesFound: "Aucune Table Trouvée",
            noTablesDesc: "Configurez les tables de votre restaurant dans les paramètres.",
            loadingTables: "Chargement des tables...",
            orderSuccess: "Commande créée avec succès!",
            orderError: "Échec de la création de la commande",
        },
        myOrdersPage: {
            title: "Mes Commandes",
            ordersCount: "commandes",
            loading: "Chargement des commandes...",
            noOrders: "Pas Encore de Commandes",
            noOrdersDesc: "Les commandes que vous créez apparaîtront ici.",
            table: "Table",
            total: "Total",
            today: "Aujourd'hui",
            yesterday: "Hier",
            markAsServed: "Marquer comme Servi",
            markAsPaid: "Marquer comme Payé",
            filterAll: "Toutes les Commandes",
            statusPending: "En attente",
            statusValidated: "Validé",
            statusPreparing: "En préparation",
            statusReady: "Prêt",
            statusServed: "Servi",
            statusPaid: "Payé",
            statusCanceled: "Annulé",
            // Order Actions
            orderActions: "Actions de la Commande",
            editOrder: "Modifier la Commande",
            editNotes: "Modifier les Notes",
            cancelOrder: "Annuler la Commande",
            deleteOrder: "Supprimer la Commande",
            viewDetails: "Voir les Détails",
            // Confirmation dialogs
            confirmCancel: "Annuler cette commande ?",
            confirmCancelDesc: "Cette action est irréversible. La cuisine sera notifiée.",
            confirmDelete: "Supprimer cette commande ?",
            confirmDeleteDesc: "Cela supprimera définitivement la commande du système.",
            confirmServed: "Marquer comme servi ?",
            confirmServedDesc: "Confirmer que cette commande a été livrée à la table.",
            confirmPaid: "Marquer comme payé ?",
            confirmPaidDesc: "Confirmer que cette commande a été payée par le client.",
            yes: "Oui",
            no: "Non",
            confirm: "Confirmer",
            cancel: "Annuler",
            // Toast messages
            orderCanceled: "Commande annulée avec succès",
            orderDeleted: "Commande supprimée avec succès",
            orderMarkedServed: "Commande marquée comme servie",
            orderMarkedPaid: "Commande marquée comme payée",
            notesUpdated: "Notes mises à jour avec succès",
            actionFailed: "Échec de l'action. Veuillez réessayer.",
            // Notes Modal
            customerNotes: "Notes du Client",
            waiterNotes: "Notes du Serveur",
            customerNotesPlaceholder: "Ajouter les préférences ou demandes du client...",
            waiterNotesPlaceholder: "Ajouter vos notes sur cette commande...",
            saveNotes: "Enregistrer les Notes",
            cancellationReason: "Raison de l'Annulation",
            cancellationReasonPlaceholder: "Pourquoi cette commande est-elle annulée ?",
        },
        profilePage: {
            title: "Profil",
            personalInfo: "Informations Personnelles",
            name: "Nom",
            email: "Email",
            phone: "Téléphone",
            role: "Rôle",
            restaurant: "Restaurant",
            memberSince: "Membre Depuis",
            settings: "Paramètres",
            language: "Langue",
            notifications: "Notifications",
            darkMode: "Mode Sombre",
            account: "Compte",
            editProfile: "Modifier le Profil",
            changePassword: "Changer le Mot de Passe",
            logout: "Déconnexion",
            logoutConfirm: "Êtes-vous sûr de vouloir vous déconnecter ?",
            version: "Version",
            support: "Aide & Support",
            privacyPolicy: "Politique de Confidentialité",
            termsOfService: "Conditions d'Utilisation",
            active: "Actif",
            inactive: "Inactif",
        },
        scanPage: {
            title: "Scanner Commande",
            subtitle: "Scannez le code QR du client pour voir sa commande",
            scanning: "Scan en cours...",
            pointCamera: "Pointez votre caméra vers le code QR",
            permissionDenied: "Permission caméra refusée",
            permissionDeniedDesc: "Veuillez autoriser l'accès à la caméra pour scanner les codes QR",
            retryPermission: "Autoriser la Caméra",
            invalidQR: "Code QR Invalide",
            invalidQRDesc: "Ce code QR ne contient pas de commande valide",
            expiredQR: "Code QR Expiré",
            expiredQRDesc: "Cette commande a expiré. Demandez au client d'en générer une nouvelle.",
            wrongRestaurant: "Mauvais Restaurant",
            wrongRestaurantDesc: "Cette commande est pour un autre restaurant",
            scanAgain: "Scanner à Nouveau",
            // Order Review
            orderReview: "Révision de la Commande",
            table: "Table",
            items: "articles",
            customerNotes: "Notes du Client",
            waiterNotes: "Notes du Serveur",
            waiterNotesPlaceholder: "Ajouter des notes sur cette commande...",
            noCustomerNotes: "Pas de notes du client",
            // Item actions
            editItem: "Modifier l'Article",
            removeItem: "Supprimer",
            confirmRemove: "Supprimer cet article ?",
            confirmRemoveDesc: "Cela supprimera l'article de la commande",
            // Edit modal
            selectVariant: "Choisir la Variante",
            selectModifiers: "Suppléments",
            quantity: "Quantité",
            specialInstructions: "Instructions Spéciales",
            specialInstructionsPlaceholder: "ex: Sans oignons, sauce extra...",
            saveChanges: "Enregistrer",
            // Order actions
            addMoreItems: "Ajouter Plus",
            confirmOrder: "Confirmer et Envoyer en Cuisine",
            orderTotal: "Total de la Commande",
            subtotal: "Sous-total",
            // Success/Error states
            orderCreated: "Commande créée avec succès !",
            orderFailed: "Échec de la création de la commande",
            creatingOrder: "Création de la commande...",
            // Empty state
            noItemsInOrder: "Aucun article dans la commande",
            noItemsDesc: "Tous les articles ont été retirés de cette commande",
        },
        kitchenPage: {
            // Dashboard
            chef: "Chef",
            pendingOrders: "En attente",
            preparingOrders: "En préparation",
            newOrders: "Nouvelles Commandes",
            inProgress: "En Cours",
            viewAll: "Voir Tout",
            noNewOrders: "Aucune nouvelle commande",
            noNewOrdersDesc: "Les nouvelles commandes apparaîtront ici",
            noPreparingOrders: "Aucune commande en cours",
            noPreparingOrdersDesc: "Les commandes en préparation apparaîtront ici",
            // Orders page
            ordersTitle: "Commandes Cuisine",
            ordersCount: "commandes",
            loading: "Chargement des commandes...",
            noOrders: "Aucune Commande",
            noOrdersDesc: "Aucune commande ne correspond à votre filtre",
            filterAll: "Tout",
            // Statuses
            statusPending: "En attente",
            statusPreparing: "En préparation",
            statusReady: "Prêt",
            // Order card
            table: "Table",
            items: "articles",
            justNow: "À l'instant",
            minutesAgo: "min",
            customerNotes: "Notes du Client",
            waiterNotes: "Notes du Serveur",
            specialNote: "Note Spéciale",
            startPreparing: "Commencer la Préparation",
            markReady: "Marquer Prêt",
            // Notifications
            newOrderAlert: "Nouvelle Commande!",
            newOrdersWaiting: "nouvelles commandes en attente",
            viewNow: "Voir Maintenant",
        }
    }
}
export default CONTENT;